package RoomReservationApp;


/**
* RoomReservationApp/_RoomReservationStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomReservation.idl
* Thursday, October 14, 2021 4:34:19 o'clock PM EDT
*/

public class _RoomReservationStub extends org.omg.CORBA.portable.ObjectImpl implements RoomReservationApp.RoomReservation
{


  /* Admin role */
  public RoomReservationApp.RMIResponse createRoom (short roomNumber, String date, String[] timeslots)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createRoom", true);
                $out.write_short (roomNumber);
                $out.write_string (date);
                RoomReservationApp.listOfTimeSlotsHelper.write ($out, timeslots);
                $in = _invoke ($out);
                RoomReservationApp.RMIResponse $result = RoomReservationApp.RMIResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createRoom (roomNumber, date, timeslots        );
            } finally {
                _releaseReply ($in);
            }
  } // createRoom

  public RoomReservationApp.RMIResponse deleteRoom (short roomNumber, String date, String[] timeslots)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deleteRoom", true);
                $out.write_short (roomNumber);
                $out.write_string (date);
                RoomReservationApp.listOfTimeSlotsHelper.write ($out, timeslots);
                $in = _invoke ($out);
                RoomReservationApp.RMIResponse $result = RoomReservationApp.RMIResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return deleteRoom (roomNumber, date, timeslots        );
            } finally {
                _releaseReply ($in);
            }
  } // deleteRoom


  /* Student role */
  public RoomReservationApp.RMIResponse bookRoom (String identifier, RoomReservationApp.Campus campusName, short roomNumber, String date, String timeslot)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("bookRoom", true);
                $out.write_string (identifier);
                RoomReservationApp.CampusHelper.write ($out, campusName);
                $out.write_short (roomNumber);
                $out.write_string (date);
                $out.write_string (timeslot);
                $in = _invoke ($out);
                RoomReservationApp.RMIResponse $result = RoomReservationApp.RMIResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return bookRoom (identifier, campusName, roomNumber, date, timeslot        );
            } finally {
                _releaseReply ($in);
            }
  } // bookRoom

  public RoomReservationApp.RMIResponse getAvailableTimeSlot (String date)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAvailableTimeSlot", true);
                $out.write_string (date);
                $in = _invoke ($out);
                RoomReservationApp.RMIResponse $result = RoomReservationApp.RMIResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAvailableTimeSlot (date        );
            } finally {
                _releaseReply ($in);
            }
  } // getAvailableTimeSlot

  public RoomReservationApp.RMIResponse cancelBooking (String identifier, String bookingId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cancelBooking", true);
                $out.write_string (identifier);
                $out.write_string (bookingId);
                $in = _invoke ($out);
                RoomReservationApp.RMIResponse $result = RoomReservationApp.RMIResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cancelBooking (identifier, bookingId        );
            } finally {
                _releaseReply ($in);
            }
  } // cancelBooking

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RoomReservationApp/RoomReservation:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RoomReservationStub
