package RoomReservationApp;


/**
* RoomReservationApp/CampusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from RoomReservation.idl
* Friday, October 15, 2021 at 3:19:28 p.m. Eastern Daylight Time
*/

abstract public class CampusHelper
{
  private static String  _id = "IDL:RoomReservationApp/Campus:1.0";

  public static void insert (org.omg.CORBA.Any a, RoomReservationApp.Campus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RoomReservationApp.Campus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (RoomReservationApp.CampusHelper.id (), "Campus", new String[] { "DVL", "KKL", "WST"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RoomReservationApp.Campus read (org.omg.CORBA.portable.InputStream istream)
  {
    return RoomReservationApp.Campus.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RoomReservationApp.Campus value)
  {
    ostream.write_long (value.value ());
  }

}
