package RoomReservationApp;

/**
* RoomReservationApp/CampusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomReservation.idl
* Thursday, October 14, 2021 4:34:19 o'clock PM EDT
*/

public final class CampusHolder implements org.omg.CORBA.portable.Streamable
{
  public RoomReservationApp.Campus value = null;

  public CampusHolder ()
  {
  }

  public CampusHolder (RoomReservationApp.Campus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RoomReservationApp.CampusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RoomReservationApp.CampusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RoomReservationApp.CampusHelper.type ();
  }

}
