package RoomReservationApp;


/**
* RoomReservationApp/Campus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomReservation.idl
* Thursday, October 14, 2021 4:34:19 o'clock PM EDT
*/

public class Campus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static RoomReservationApp.Campus[] __array = new RoomReservationApp.Campus [__size];

  public static final int _DVL = 0;
  public static final RoomReservationApp.Campus DVL = new RoomReservationApp.Campus(_DVL);
  public static final int _KKL = 1;
  public static final RoomReservationApp.Campus KKL = new RoomReservationApp.Campus(_KKL);
  public static final int _WST = 2;
  public static final RoomReservationApp.Campus WST = new RoomReservationApp.Campus(_WST);

  public int value ()
  {
    return __value;
  }

  public static RoomReservationApp.Campus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Campus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Campus
