package RoomReservationApp;


/**
* RoomReservationApp/listOfTimeSlotsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from RoomReservation.idl
* Thursday, October 21, 2021 at 3:43:22 p.m. Eastern Daylight Time
*/

public final class listOfTimeSlotsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public listOfTimeSlotsHolder ()
  {
  }

  public listOfTimeSlotsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RoomReservationApp.listOfTimeSlotsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RoomReservationApp.listOfTimeSlotsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RoomReservationApp.listOfTimeSlotsHelper.type ();
  }

}
