package RoomReservationApp;

/**
* RoomReservationApp/RMIResponseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomReservation.idl
* Thursday, October 14, 2021 4:34:19 o'clock PM EDT
*/

public final class RMIResponseHolder implements org.omg.CORBA.portable.Streamable
{
  public RoomReservationApp.RMIResponse value = null;

  public RMIResponseHolder ()
  {
  }

  public RMIResponseHolder (RoomReservationApp.RMIResponse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RoomReservationApp.RMIResponseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RoomReservationApp.RMIResponseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RoomReservationApp.RMIResponseHelper.type ();
  }

}
