package RoomReservationApp;


/**
* RoomReservationApp/RMIResponse.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from RoomReservation.idl
* Friday, October 15, 2021 at 4:44:49 p.m. Eastern Daylight Time
*/

public final class RMIResponse implements org.omg.CORBA.portable.IDLEntity
{
  public String message = null;
  public String date = null;
  public String requestType = null;
  public String requestParameters = null;
  public boolean status = false;

  public RMIResponse ()
  {
  } // ctor

  public RMIResponse (String _message, String _date, String _requestType, String _requestParameters, boolean _status)
  {
    message = _message;
    date = _date;
    requestType = _requestType;
    requestParameters = _requestParameters;
    status = _status;
  } // ctor

} // class RMIResponse
