package RoomReservationApp;


/**
* RoomReservationApp/RMIResponse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomReservation.idl
* Thursday, October 14, 2021 4:34:19 o'clock PM EDT
*/

public final class RMIResponse implements org.omg.CORBA.portable.IDLEntity
{
  public String message = null;
  public String date = null;
  public String requestType = null;
  public String requestParameters = null;
  public boolean status = false;

  public RMIResponse ()
  {
  } // ctor

  public RMIResponse (String _message, String _date, String _requestType, String _requestParameters, boolean _status)
  {
    message = _message;
    date = _date;
    requestType = _requestType;
    requestParameters = _requestParameters;
    status = _status;
  } // ctor

} // class RMIResponse
