package RoomReservationApp;


/**
* RoomReservationApp/RoomReservationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from RoomReservation.idl
* Friday, October 15, 2021 at 4:44:49 p.m. Eastern Daylight Time
*/

public interface RoomReservationOperations 
{

  /* Admin role */
  RoomReservationApp.RMIResponse createRoom (short roomNumber, String date, String[] timeslots);
  RoomReservationApp.RMIResponse deleteRoom (short roomNumber, String date, String[] timeslots);

  /* Student role */
  RoomReservationApp.RMIResponse bookRoom (String identifier, String campusName, short roomNumber, String date, String timeslot);
  RoomReservationApp.RMIResponse getAvailableTimeSlot (String date);
  RoomReservationApp.RMIResponse cancelBooking (String identifier, String bookingId);
  void shutdown ();
} // interface RoomReservationOperations
