package RoomReservationApp;


/**
* RoomReservationApp/RoomReservationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from RoomReservation.idl
* Thursday, October 21, 2021 at 3:43:22 p.m. Eastern Daylight Time
*/

public interface RoomReservationOperations 
{

  /* Admin role */
  RoomReservationApp.CorbaResponse createRoom (short roomNumber, String date, String[] timeslots);
  RoomReservationApp.CorbaResponse deleteRoom (short roomNumber, String date, String[] timeslots);

  /* Student role */
  RoomReservationApp.CorbaResponse bookRoom (String identifier, String campusName, short roomNumber, String date, String timeslot);
  RoomReservationApp.CorbaResponse getAvailableTimeSlot (String date);
  RoomReservationApp.CorbaResponse cancelBooking (String identifier, String bookingId);
  RoomReservationApp.CorbaResponse changeReservation (String identifier, String bookingId, String newCampusName, short newRoomNumber, String newDate, String newTimeslot);
  void shutdown ();
} // interface RoomReservationOperations
