package RoomReservationApp;


/**
* RoomReservationApp/RoomReservation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomReservation.idl
* Thursday, October 14, 2021 4:34:19 o'clock PM EDT
*/

public interface RoomReservation extends RoomReservationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RoomReservation
