package RoomReservationApp;


/**
* RoomReservationApp/RoomReservation.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from RoomReservation.idl
* Thursday, October 21, 2021 at 3:43:22 p.m. Eastern Daylight Time
*/

public interface RoomReservation extends RoomReservationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RoomReservation
