module RoomReservationApp{
    struct CorbaResponse {
        string message;
        string date;
        string requestType;
        string requestParameters;
        boolean status;
    };
    typedef sequence <string> listOfTimeSlots;
    interface RoomReservation{
        /* Admin role */
        CorbaResponse createRoom(in short roomNumber, in string date, in listOfTimeSlots timeslots);
        CorbaResponse deleteRoom(in short roomNumber, in string date, in listOfTimeSlots timeslots);

        /* Student role */
        CorbaResponse bookRoom(in string identifier, in string campusName, in short roomNumber, in string date, in string timeslot);
        CorbaResponse getAvailableTimeSlot(in string date);
        CorbaResponse cancelBooking(in string identifier, in string bookingId);
        CorbaResponse changeReservation(in string identifier, in string bookingId, in string newCampusName, in short newRoomNumber, in string newDate, in string newTimeslot);
        oneway void shutdown();
    };
};

