module RoomReservationApp{
    struct RMIResponse {
        string message;
        string date;
        string requestType;
        string requestParameters;
        boolean status;
    };
    typedef sequence <string> listOfTimeSlots;
    interface RoomReservation{
        /* Admin role */
        RMIResponse createRoom(in short roomNumber, in string date, in listOfTimeSlots timeslots);
        RMIResponse deleteRoom(in short roomNumber, in string date, in listOfTimeSlots timeslots);

        /* Student role */
        RMIResponse bookRoom(in string identifier, in string campusName, in short roomNumber, in string date, in string timeslot);
        RMIResponse getAvailableTimeSlot(in string date);
        RMIResponse cancelBooking(in string identifier, in string bookingId);
        RMIResponse changeReservation(in string identifier, in string bookingId, in string newCampusName, in short newRoomNumber, in string newDate, in string newTimeslot);
        oneway void shutdown();
    };
};