package RoomReservationApp;

/**
* RoomReservationApp/RoomReservationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/com/roomreservation/RoomReservation.idl
* Wednesday, October 13, 2021 6:41:41 o'clock PM EDT
*/

public final class RoomReservationHolder implements org.omg.CORBA.portable.Streamable
{
  public RoomReservationApp.RoomReservation value = null;

  public RoomReservationHolder ()
  {
  }

  public RoomReservationHolder (RoomReservationApp.RoomReservation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RoomReservationApp.RoomReservationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RoomReservationApp.RoomReservationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RoomReservationApp.RoomReservationHelper.type ();
  }

}
