package RoomReservationApp;


/**
* RoomReservationApp/RoomReservationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/com/roomreservation/RoomReservation.idl
* Wednesday, October 13, 2021 6:41:41 o'clock PM EDT
*/

public abstract class RoomReservationPOA extends org.omg.PortableServer.Servant
 implements RoomReservationApp.RoomReservationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createRoom", new java.lang.Integer (0));
    _methods.put ("deleteRoom", new java.lang.Integer (1));
    _methods.put ("bookRoom", new java.lang.Integer (2));
    _methods.put ("getAvailableTimeSlot", new java.lang.Integer (3));
    _methods.put ("cancelBooking", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /* Admin role */
       case 0:  // RoomReservationApp/RoomReservation/createRoom
       {
         short roomNumber = in.read_short ();
         String date = in.read_string ();
         String timeslots[] = RoomReservationApp.listOfTimeSlotsHelper.read (in);
         RoomReservationApp.RMIResponse $result = null;
         $result = this.createRoom (roomNumber, date, timeslots);
         out = $rh.createReply();
         RoomReservationApp.RMIResponseHelper.write (out, $result);
         break;
       }

       case 1:  // RoomReservationApp/RoomReservation/deleteRoom
       {
         short roomNumber = in.read_short ();
         String date = in.read_string ();
         String timeslots[] = RoomReservationApp.listOfTimeSlotsHelper.read (in);
         RoomReservationApp.RMIResponse $result = null;
         $result = this.deleteRoom (roomNumber, date, timeslots);
         out = $rh.createReply();
         RoomReservationApp.RMIResponseHelper.write (out, $result);
         break;
       }


  /* Student role */
       case 2:  // RoomReservationApp/RoomReservation/bookRoom
       {
         String identifier = in.read_string ();
         RoomReservationApp.Campus campusName = RoomReservationApp.CampusHelper.read (in);
         short roomNumber = in.read_short ();
         String date = in.read_string ();
         String timeslot = in.read_string ();
         RoomReservationApp.RMIResponse $result = null;
         $result = this.bookRoom (identifier, campusName, roomNumber, date, timeslot);
         out = $rh.createReply();
         RoomReservationApp.RMIResponseHelper.write (out, $result);
         break;
       }

       case 3:  // RoomReservationApp/RoomReservation/getAvailableTimeSlot
       {
         String date = in.read_string ();
         RoomReservationApp.RMIResponse $result = null;
         $result = this.getAvailableTimeSlot (date);
         out = $rh.createReply();
         RoomReservationApp.RMIResponseHelper.write (out, $result);
         break;
       }

       case 4:  // RoomReservationApp/RoomReservation/cancelBooking
       {
         String identifier = in.read_string ();
         String bookingId = in.read_string ();
         RoomReservationApp.RMIResponse $result = null;
         $result = this.cancelBooking (identifier, bookingId);
         out = $rh.createReply();
         RoomReservationApp.RMIResponseHelper.write (out, $result);
         break;
       }

       case 5:  // RoomReservationApp/RoomReservation/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RoomReservationApp/RoomReservation:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RoomReservation _this() 
  {
    return RoomReservationHelper.narrow(
    super._this_object());
  }

  public RoomReservation _this(org.omg.CORBA.ORB orb) 
  {
    return RoomReservationHelper.narrow(
    super._this_object(orb));
  }


} // class RoomReservationPOA
