package RoomReservationApp;


/**
* RoomReservationApp/RoomReservationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/com/roomreservation/RoomReservation.idl
* Wednesday, October 13, 2021 6:41:41 o'clock PM EDT
*/

public interface RoomReservationOperations 
{

  /* Admin role */
  RoomReservationApp.RMIResponse createRoom (short roomNumber, String date, String[] timeslots);
  RoomReservationApp.RMIResponse deleteRoom (short roomNumber, String date, String[] timeslots);

  /* Student role */
  RoomReservationApp.RMIResponse bookRoom (String identifier, RoomReservationApp.Campus campusName, short roomNumber, String date, String timeslot);
  RoomReservationApp.RMIResponse getAvailableTimeSlot (String date);
  RoomReservationApp.RMIResponse cancelBooking (String identifier, String bookingId);
  void shutdown ();
} // interface RoomReservationOperations
