package RoomReservationApp;


/**
* RoomReservationApp/RoomReservation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/com/roomreservation/RoomReservation.idl
* Wednesday, October 13, 2021 6:41:41 o'clock PM EDT
*/

public interface RoomReservation extends RoomReservationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RoomReservation
