// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requestObject.proto

package protobuf.protos;

public final class RequestObjectProtos {
  private RequestObjectProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_RequestObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_RequestObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023requestObject.proto\022\010protobuf\"\216\001\n\rRequ" +
      "estObject\022\016\n\006action\030\001 \002(\t\022\021\n\tbookingId\030\002" +
      " \001(\t\022\014\n\004date\030\003 \001(\t\022\022\n\ncampusName\030\004 \001(\t\022\022" +
      "\n\nroomNumber\030\005 \001(\005\022\020\n\010timeslot\030\006 \001(\t\022\022\n\n" +
      "identifier\030\007 \001(\tB(\n\017protobuf.protosB\023Req" +
      "uestObjectProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_RequestObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_RequestObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_RequestObject_descriptor,
        new java.lang.String[] { "Action", "BookingId", "Date", "CampusName", "RoomNumber", "Timeslot", "Identifier", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
