// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responseObject.proto

package protobuf.protos;

public final class ResponseObjectProtos {
  private ResponseObjectProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ResponseObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_ResponseObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024responseObject.proto\022\010protobuf\"s\n\016Resp" +
      "onseObject\022\017\n\007message\030\001 \002(\t\022\020\n\010dateTime\030" +
      "\002 \002(\t\022\023\n\013requestType\030\003 \002(\t\022\031\n\021requestPar" +
      "ameters\030\004 \002(\t\022\016\n\006status\030\005 \002(\010B)\n\017protobu" +
      "f.protosB\024ResponseObjectProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_ResponseObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_ResponseObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_ResponseObject_descriptor,
        new java.lang.String[] { "Message", "DateTime", "RequestType", "RequestParameters", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
